pipeline {
    agent any

    stages {
        stage("Build-Backend") {
            steps {
                bat '''
                    docker pull golang:1.21
                    docker run --rm -v %cd%:/app -w /app/bugtracker-backend golang:1.21 sh -c "go test -v ./..."
                '''
            }
        }

        stage("Test-Frontend") {
            steps {
                bat '''
                    docker pull node:20-alpine
                    docker run --rm -v %cd%:/app -w /app/bugtracker-frontend node:20-alpine sh -c "npm ci && npm test"
                '''
            }
        }

        // stage("Deploy") {
        //     steps {
        //         echo "Deploying the application"
        //     }
        // }
    }
}
