pipeline {
    agent none

    stages {
        stage("Build-Backend") {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }

        stage("bugtracker-frontend") {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
        }

        // stage("Deploy") {
        //     agent any
        //     steps {
        //         echo "Deploying the application"
        //     }
        // }
    }
}
