name: CI

on:
  push:
    branches:
      - main
      - githubActions # Add your current branch
  pull_request:
    branches:
      - main # This means it will run on any PR targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Go for backend
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true
          cache-dependency-path: bugtracker-backend/go.sum

      # Setup Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            bugtracker-frontend/package-lock.json
            tests/package-lock.json

      # Build backend
      - name: Build backend
        working-directory: ./bugtracker-backend
        run: |
          go mod download
          go build -v ./...

      # Run backend tests
      - name: Test backend
        working-directory: ./bugtracker-backend
        run: |
          go test -json -coverprofile=coverage.out -covermode=atomic ./... > test-results.json
          go tool cover -func=coverage.out > coverage.txt
          echo "## Go Test Coverage" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      # Generate test report
      - name: Generate test report
        uses: guyarb/golang-test-annotations@v0.7.0
        if: always()
        with:
          test-results: bugtracker-backend/test-results.json
          package-name: bugtracker-backend

      # Build frontend
      - name: Build frontend
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm run build
